"use client";
export const projects = [
  {
    id: 1,
    title: "Moos Barber",
    category: "Mobile App",
    type: "mobile",
    iOS_Link: "https://apps.apple.com/us/app/moos-barber-app/id6449462238",
    Android_Link: "https://play.google.com/store/apps/details?id=com.wn.hairtattoo&hl=en",
    description: "Enjoy the best Barbering services with MOOS BARBERS. Get a local's insight into the Barber professions & Saloons & plan your visit by contacting them ahead of time. Using this app, you can find direct Barber professions & Saloons.",
    image: "/ecommerce-mobile-app-mockup.png",
    technologies: ["iOS", "Android", "Google Maps", "Firebase", "Braintree", "PayPal", "Alamofire"],
    client: "United Kingdom",
    results: ["300% increase in user engagement", "50% reduction in cart abandonment", "4.8/5 app store rating"],
    caseStudy: {
      challenge: "Moos Barber needed a mobile platform that would make Barbering services accessible and engaging for everyday consumers while tracking their preferences.",
      solution: "We developed a React Native app with AI-powered Barber recommendations, appointment scheduling, and user-friendly interfaces to encourage bookings.",
      outcome: "The app achieved over 100K downloads in the first 6 months, with users reporting 40% more bookings and high engagement with the Barber profiles.",
      timeline: "5 months",
      teamSize: "6 developers",
      projectDetails: "Multivendor Barber apps for Customers & professionals barbers/salons.",
      AppHighlights: ["Discover professional barbers and salons nearby", "Book appointments online instantly","Secure Payments – Safe and easy booking", "Connect directly with barbers and salon professionals", "Use the app in both Arabic and English for your convenience"],
      technologies: ["iOS", "Android","Figma","Laravel","API Integration (REST)"],
      thirdPartyServices: ["Google Maps", "Firebase", "Braintree", "PayPal", "Alamofire"],
    },
  },
  {
    id: 2,
    title: "Wyld",
    category: "Mobile App",
    type: "mobile",
    iOS_Link: "https://apps.apple.com/us/app/wyld-stay/id6449990424",
    Android_Link: "https://play.google.com/store/apps/details?id=com.wn.hairtattoo&hl=en",

    description: "Enjoy the best vacation experiences with WYLD Camps. Get a local's insight into the Camps you plan to visit before your vacation by contacting them ahead of time. Using this app, you can find direct venders for summer camps.",
    image: "/wyld-app.jpg",
    technologies: ["iOS", "Android", "Google Maps", "Firebase", "Authorize.Net Accept", "Alamofire"],
    client: "USA",
    results: ["300% increase in user engagement", "50% reduction in cart abandonment", "4.8/5 app store rating"],
    caseStudy: {
      challenge: "Moos Barber needed a mobile platform that would make Barbering services accessible and engaging for everyday consumers while tracking their preferences.",
      solution: "We developed a React Native app with AI-powered Barber recommendations, appointment scheduling, and user-friendly interfaces to encourage bookings.",
      outcome: "The app achieved over 100K downloads in the first 6 months, with users reporting 40% more bookings and high engagement with the Barber profiles.",
      timeline: "5 months",
      teamSize: "6 developers",
      projectDetails: "Camp Booking for Customers and Venders.",
      AppHighlights: ["Discover Camps – Browse curated summer camps with detailed info and reviews", "Direct Vendor Access – Connect with camp organizers before booking", "Secure Payments – Safe and easy booking", "Seamless Booking – Real-time availability and instant confirmations", "Local Insights – Get personalized tips from camp vendors and hosts", "User-Friendly Experience – Simple, fast, and intuitive design"],
      technologies: ["iOS", "Android","Figma","Laravel","API Integration (REST)"],
      thirdPartyServices: ["Google Maps", "Firebase", "Authorize.Net Accept", "Alamofire"],
    },
  },
  {
    id: 3,
    title: "Fly Elite",
    category: "Mobile App",
    type: "mobile",
    iOS_Link: "https://apps.apple.com/kw/app/flyelite/id6468663680",
    Android_Link: "https://play.google.com/store/apps/details?id=com.booking.flyelitejets&hl=en",

    description: "Enjoy the best Jet vacation experiences around the globe with Fly Elite. Using this app, you can find best booking experience & make the most of your itinerary by planning efficiently.",
    image: "/flyelite.jpg",
    technologies: ["iOS", "Android", "Firebase", "Stripe", "Twilio"],
    client: "Dubai, UAE",
    results: ["300% increase in user engagement", "50% reduction in cart abandonment", "4.8/5 app store rating"],
    caseStudy: {
      challenge: "Moos Barber needed a mobile platform that would make Barbering services accessible and engaging for everyday consumers while tracking their preferences.",
      solution: "We developed a React Native app with AI-powered Barber recommendations, appointment scheduling, and user-friendly interfaces to encourage bookings.",
      outcome: "The app achieved over 100K downloads in the first 6 months, with users reporting 40% more bookings and high engagement with the Barber profiles.",
      timeline: "4 months",
      teamSize: "6 developers",
      projectDetails: "Jet Booking apps",
      AppHighlights: ["•	Discover professional barbers and salons nearby", "•	Book appointments online instantly", "•	Connect directly with barbers and salon professionals", "•	Use the app in both Arabic and English for your convenience"],
      technologies: ["React Native", "Node.js", "MongoDB", "TensorFlow", "AWS", "Stripe"],
      thirdPartyServices: ["Firebase", "Stripe", "Twilio"],
    },
  },
  {
    id: 4,
    title: "G8pass",
    category: "Mobile App",
    type: "mobile",
     iOS_Link: "https://apps.apple.com/rs/app/g8pass-app/id6447676497",
    Android_Link: "https://play.google.com/store/apps/details?id=com.lvm.g8pass&hl=en",

    description: "G8PASS is the best Society Management Apps & backend Software. It provides to manage housing, apartments security, visitor management and facility management etc. Now managing your Housing Society is simple.",
    image: "/gatepass-app.jpg",
    technologies: ["iOS", "Android", "Alamofire", "Pushy"],
    client: "Germany & Dubai - UAE",
    results: ["300% increase in user engagement", "50% reduction in cart abandonment", "4.8/5 app store rating"],
    caseStudy: {
      challenge: "Moos Barber needed a mobile platform that would make Barbering services accessible and engaging for everyday consumers while tracking their preferences.",
      solution: "We developed a React Native app with AI-powered Barber recommendations, appointment scheduling, and user-friendly interfaces to encourage bookings.",
      outcome: "The app achieved over 100K downloads in the first 6 months, with users reporting 40% more bookings and high engagement with the Barber profiles.",
      timeline: "4 months",
      teamSize: "6 developers",
      projectDetails: "Society Management Apps for Customers, Security Guards & web software for society management staff",
      AppHighlights: ["Resident App – Pay maintenance bills, raise complaints, book amenities, track visitors.", "Security Guard App – Quick visitor entry/exit, emergency alerts, staff attendance.", "Society Staff Web Software – Manage members, finances, facility bookings, and reports.", "Communication Hub – Announcements, polls, and notice board for residents.", "Digital Payments – Easy online payments for maintenance & utilities.", "Smart Dashboard – Real-time analytics and reports for management committees.", "Instant Alerts – SMS, push notifications & emergency notifications.", "Facility Management – Track bookings for clubhouse, gym, parking, etc.", ""],
      technologies: ["iOS", "Android"],
      thirdPartyServices: ["Alamofire", "Pushy"],
    },
  },
  // {
  //   id: 5,
  //   title: "Binsina Pharmacy",
  //   category: "Mobile App",
  //   type: "mobile",
  //    iOS_Link: "https://apps.apple.com/in/app/binsina/id1633403246",
  //   Android_Link: "https://play.google.com/store/search?q=Binsina%20Pharmacy&c=apps&hl=en",

  //   description: "BinSina is a pharmacy dedicated to offering exceptional and personalized services in the field of health, wellness, and nutrition. We pride ourselves on our unique approach to customer care, where our pharmacists are more than just a professional advisor, but like a trusted neighbour, a knowledgeable friend, or a caring family member.",
  //   image: "/Binsin.png",
  //   technologies: ["iOS", "Android", "Alamofire", "Tamara", "Knet", "Tabby"],
  //   client: "Germany & Dubai - UAE",
  //   results: ["300% increase in user engagement", "50% reduction in cart abandonment", "4.8/5 app store rating"],
  //   caseStudy: {
  //     challenge: "Moos Barber needed a mobile platform that would make Barbering services accessible and engaging for everyday consumers while tracking their preferences.",
  //     solution: "We developed a React Native app with AI-powered Barber recommendations, appointment scheduling, and user-friendly interfaces to encourage bookings.",
  //     outcome: "The app achieved over 100K downloads in the first 6 months, with users reporting 40% more bookings and high engagement with the Barber profiles.",
  //     timeline: "4 months",
  //     teamSize: "6 developers",
  //     projectDetails: "Society Management Apps for Customers, Security Guards & web software for society management staff",
  //     AppHighlights: ["Resident App – Pay maintenance bills, raise complaints, book amenities, track visitors.", "Security Guard App – Quick visitor entry/exit, emergency alerts, staff attendance.", "Society Staff Web Software – Manage members, finances, facility bookings, and reports.", "Communication Hub – Announcements, polls, and notice board for residents.", "Digital Payments – Easy online payments for maintenance & utilities.", "Smart Dashboard – Real-time analytics and reports for management committees.", "Instant Alerts – SMS, push notifications & emergency notifications.", "Facility Management – Track bookings for clubhouse, gym, parking, etc.", ""],
  //     technologies: ["iOS", "Android"],
  //     thirdPartyServices: ["Alamofire", "Pushy"],
  //   },
  // },
  // {
  //   id: 6,
  //   title: "SAMRAT",
  //   category: "Mobile App",
  //   type: "mobile",
  //   iOS_Link: "https://apps.apple.com/us/app/samrat/id1556206159",
  //   Android_Link: "https://play.google.com/store/apps/details?id=com.si.samrat&hl=en",

  //   description: "Samrat enables users to plan and book private music events (“samarat”) with full control over their experience—selecting preferred singers, instrumentalists, and audio services—without intermediaries. Online booking system with payment gateway.",
  //   image: "/SAMRAT.png",
  //   technologies: ["iOS", "Android", "Alamofire", "Knet", "OneSignal", "Firebase"],
  //   client: "Germany & Dubai - UAE",
  //   results: ["300% increase in user engagement", "50% reduction in cart abandonment", "4.8/5 app store rating"],
  //   caseStudy: {
  //     challenge: "Moos Barber needed a mobile platform that would make Barbering services accessible and engaging for everyday consumers while tracking their preferences.",
  //     solution: "We developed a React Native app with AI-powered Barber recommendations, appointment scheduling, and user-friendly interfaces to encourage bookings.",
  //     outcome: "The app achieved over 100K downloads in the first 6 months, with users reporting 40% more bookings and high engagement with the Barber profiles.",
  //     timeline: "4 months",
  //     teamSize: "6 developers",
  //     projectDetails: "Society Management Apps for Customers, Security Guards & web software for society management staff",
  //     AppHighlights: ["Resident App – Pay maintenance bills, raise complaints, book amenities, track visitors.", "Security Guard App – Quick visitor entry/exit, emergency alerts, staff attendance.", "Society Staff Web Software – Manage members, finances, facility bookings, and reports.", "Communication Hub – Announcements, polls, and notice board for residents.", "Digital Payments – Easy online payments for maintenance & utilities.", "Smart Dashboard – Real-time analytics and reports for management committees.", "Instant Alerts – SMS, push notifications & emergency notifications.", "Facility Management – Track bookings for clubhouse, gym, parking, etc.", ""],
  //     technologies: ["iOS", "Android"],
  //     thirdPartyServices: ["Alamofire", "Pushy"],
  //   },
  // },
  {
    id: 7,
    title: "Wheat Grass Restaurant",
    category: "Mobile App",
    type: "mobile",
     iOS_Link: "https://apps.apple.com/in/app/wheat-grass-restaurant/id1496306028",
    Android_Link: "https://play.google.com/store/search?q=Wheat%20Grass%20Restaurant&c=apps&hl=en",

    description: "A free, multilingual (Arabic & English) app aimed at health-conscious users, offering organic wheatgrass juice and other wellness products. It’s Healthy-Food Ordering App.",
    image: "/Wheat Grass.png",
    technologies: ["iOS", "Android", "Alamofire", "Knet", "OneSignal", "Firebase"],
    client: "Germany & Dubai - UAE",
    results: ["300% increase in user engagement", "50% reduction in cart abandonment", "4.8/5 app store rating"],
    caseStudy: {
      challenge: "Moos Barber needed a mobile platform that would make Barbering services accessible and engaging for everyday consumers while tracking their preferences.",
      solution: "We developed a React Native app with AI-powered Barber recommendations, appointment scheduling, and user-friendly interfaces to encourage bookings.",
      outcome: "The app achieved over 100K downloads in the first 6 months, with users reporting 40% more bookings and high engagement with the Barber profiles.",
      timeline: "4 months",
      teamSize: "6 developers",
      projectDetails: "Society Management Apps for Customers, Security Guards & web software for society management staff",
      AppHighlights: ["Resident App – Pay maintenance bills, raise complaints, book amenities, track visitors.", "Security Guard App – Quick visitor entry/exit, emergency alerts, staff attendance.", "Society Staff Web Software – Manage members, finances, facility bookings, and reports.", "Communication Hub – Announcements, polls, and notice board for residents.", "Digital Payments – Easy online payments for maintenance & utilities.", "Smart Dashboard – Real-time analytics and reports for management committees.", "Instant Alerts – SMS, push notifications & emergency notifications.", "Facility Management – Track bookings for clubhouse, gym, parking, etc.", ""],
      technologies: ["iOS", "Android"],
      thirdPartyServices: ["Alamofire", "Pushy"],
    },
  },
  {
    id: 8,
    title: "Blipd",
    category: "Mobile App",
    type: "mobile",
    iOS_Link: "https://apps.apple.com/us/app/blipd/id934985367",
    Android_Link: "",
    
    description: "Friends can share their location with each other in real time. Easily find each other in a crowded venue, in the city, or in your neighborhood. Find new friends, create groups with them and chat, voice and video call. Using Google Maps for location and show Blipd.",
    image: "/Blipd.png",
    technologies: ["iOS", "Alamofire", "OneSignal", "Firebase","Sendbird","Google Place API","Socket.IO","Apple MapKit"],
    client: "USA",
    results: ["300% increase in user engagement", "50% reduction in cart abandonment", "4.8/5 app store rating"],
    caseStudy: {
      challenge: "Moos Barber needed a mobile platform that would make Barbering services accessible and engaging for everyday consumers while tracking their preferences.",
      solution: "We developed a React Native app with AI-powered Barber recommendations, appointment scheduling, and user-friendly interfaces to encourage bookings.",
      outcome: "The app achieved over 100K downloads in the first 6 months, with users reporting 40% more bookings and high engagement with the Barber profiles.",
      timeline: "4 months",
      teamSize: "6 developers",
      projectDetails: "Society Management Apps for Customers, Security Guards & web software for society management staff",
      AppHighlights: ["Resident App – Pay maintenance bills, raise complaints, book amenities, track visitors.", "Security Guard App – Quick visitor entry/exit, emergency alerts, staff attendance.", "Society Staff Web Software – Manage members, finances, facility bookings, and reports.", "Communication Hub – Announcements, polls, and notice board for residents.", "Digital Payments – Easy online payments for maintenance & utilities.", "Smart Dashboard – Real-time analytics and reports for management committees.", "Instant Alerts – SMS, push notifications & emergency notifications.", "Facility Management – Track bookings for clubhouse, gym, parking, etc.", ""],
      technologies: ["iOS", "Android"],
      thirdPartyServices: ["Alamofire", "Pushy"],
    },
  },
  // {
  //   id: 9,
  //   title: "Flock (Social Networking App)",
  //   category: "Mobile App",
  //    iOS_Link: "https://apps.apple.com/us/app/flock-social-inc/id1630303260",
  //   Android_Link: "",
  //   type: "mobile",
  //   description: "A team messaging platform that includes one-on-one chats, group channels, voice/video calls. The location of any post, events and group created is visible on a map. Using MapBox for location and show events.",
  //   image: "/Flock.png",
  //   technologies: ["iOS", "Alamofire", "Firebase","Sendbird","MapBox","Apple MapKit"],
  //   client: "USA",
  //   results: ["300% increase in user engagement", "50% reduction in cart abandonment", "4.8/5 app store rating"],
  //   caseStudy: {
  //     challenge: "Moos Barber needed a mobile platform that would make Barbering services accessible and engaging for everyday consumers while tracking their preferences.",
  //     solution: "We developed a React Native app with AI-powered Barber recommendations, appointment scheduling, and user-friendly interfaces to encourage bookings.",
  //     outcome: "The app achieved over 100K downloads in the first 6 months, with users reporting 40% more bookings and high engagement with the Barber profiles.",
  //     timeline: "4 months",
  //     teamSize: "6 developers",
  //     projectDetails: "Society Management Apps for Customers, Security Guards & web software for society management staff",
  //     AppHighlights: ["Resident App – Pay maintenance bills, raise complaints, book amenities, track visitors.", "Security Guard App – Quick visitor entry/exit, emergency alerts, staff attendance.", "Society Staff Web Software – Manage members, finances, facility bookings, and reports.", "Communication Hub – Announcements, polls, and notice board for residents.", "Digital Payments – Easy online payments for maintenance & utilities.", "Smart Dashboard – Real-time analytics and reports for management committees.", "Instant Alerts – SMS, push notifications & emergency notifications.", "Facility Management – Track bookings for clubhouse, gym, parking, etc.", ""],
  //     technologies: ["iOS", "Android"],
  //     thirdPartyServices: ["Alamofire", "Pushy"],
  //   },
  // },
  {
    id: 10,
    title: "GFC Global Health",
    category: "Mobile App",
    iOS_Link: "https://apps.apple.com/in/app/gfc-globalhealth/id6448429453",
    Android_Link: "https://play.google.com/store/apps/details?id=com.gfc.globalhealth&hl=en_IN",
    type: "mobile",
    description: "GFC application is for hospital management. Any patient can directly meet the doctor and make chat, voice and video calls. Patient can book appointment from app.",
    image: "/GFC.png",
    technologies: ["iOS", "Alamofire", "Firebase","quickblox"],
    client: "Iraq",
    results: ["300% increase in user engagement", "50% reduction in cart abandonment", "4.8/5 app store rating"],
    caseStudy: {
      challenge: "Moos Barber needed a mobile platform that would make Barbering services accessible and engaging for everyday consumers while tracking their preferences.",
      solution: "We developed a React Native app with AI-powered Barber recommendations, appointment scheduling, and user-friendly interfaces to encourage bookings.",
      outcome: "The app achieved over 100K downloads in the first 6 months, with users reporting 40% more bookings and high engagement with the Barber profiles.",
      timeline: "4 months",
      teamSize: "6 developers",
      projectDetails: "Society Management Apps for Customers, Security Guards & web software for society management staff",
      AppHighlights: ["Resident App – Pay maintenance bills, raise complaints, book amenities, track visitors.", "Security Guard App – Quick visitor entry/exit, emergency alerts, staff attendance.", "Society Staff Web Software – Manage members, finances, facility bookings, and reports.", "Communication Hub – Announcements, polls, and notice board for residents.", "Digital Payments – Easy online payments for maintenance & utilities.", "Smart Dashboard – Real-time analytics and reports for management committees.", "Instant Alerts – SMS, push notifications & emergency notifications.", "Facility Management – Track bookings for clubhouse, gym, parking, etc.", ""],
      technologies: ["iOS", "Android"],
      thirdPartyServices: ["Alamofire", "Pushy"],
    },
  },
  // {
  //   id: 11,
  //   title: "Dubai Harbour Marinas",
  //   category: "Mobile App",
  //    iOS_Link: "https://apps.apple.com/us/app/dubai-harbour-marinas/id6739635049",
  //   Android_Link: "https://play.google.com/store/apps/details?id=com.dubai.harbour&hl=en_IN",
  //   type: "mobile",
  //   description: "The new Dubai Harbour Marinas mobile app is designed to ensure an impeccable docking and seafront journey. Engaging and intuitive, the fully integrated app will allow marina members to access a wide range of information and request a host of services at their fingertips. The app works seamlessly across all mobile devices and the user-friendly navigation ensures easy access to key, frequently visited sections.",
  //   image: "/DHM.png",
  //   technologies: ["iOS", "Alamofire", "Firebase","One Single","NISDK"],
  //   client: "Dubai",
  //   results: ["300% increase in user engagement", "50% reduction in cart abandonment", "4.8/5 app store rating"],
  //   caseStudy: {
  //     challenge: "Moos Barber needed a mobile platform that would make Barbering services accessible and engaging for everyday consumers while tracking their preferences.",
  //     solution: "We developed a React Native app with AI-powered Barber recommendations, appointment scheduling, and user-friendly interfaces to encourage bookings.",
  //     outcome: "The app achieved over 100K downloads in the first 6 months, with users reporting 40% more bookings and high engagement with the Barber profiles.",
  //     timeline: "4 months",
  //     teamSize: "6 developers",
  //     projectDetails: "Society Management Apps for Customers, Security Guards & web software for society management staff",
  //     AppHighlights: ["Resident App – Pay maintenance bills, raise complaints, book amenities, track visitors.", "Security Guard App – Quick visitor entry/exit, emergency alerts, staff attendance.", "Society Staff Web Software – Manage members, finances, facility bookings, and reports.", "Communication Hub – Announcements, polls, and notice board for residents.", "Digital Payments – Easy online payments for maintenance & utilities.", "Smart Dashboard – Real-time analytics and reports for management committees.", "Instant Alerts – SMS, push notifications & emergency notifications.", "Facility Management – Track bookings for clubhouse, gym, parking, etc.", ""],
  //     technologies: ["iOS", "Android"],
  //     thirdPartyServices: ["Alamofire", "Pushy"],
  //   },
  // },
  // {
  //   id: 12,
  //   title: "Travel-Insurance",
  //   category: "Mobile App",
  //    iOS_Link: "https://apps.apple.com/us/app/dubai-harbour-marinas/id6739635049",
  //   Android_Link: "https://play.google.com/store/apps/details?id=com.dubai.harbour&hl=en_IN",

  //   type: "mobile",
  //   description: "Wayak is a modern travel insurance and safety app designed for today’s travelers. It offers global coverage across Europe, USA, Canada, Asia, the Middle East, and more, with flexible plans for every zone and period. Travelers can easily make secure online payments and tailor their insurance by selecting their region of residence. The app also provides real-time safety alerts, emergency contacts, and helpful travel tips to ensure a safe journey. With Wayak, you can explore the world with confidence and complete peace of mind.",
  //   image: "/Travel-Insurance.png",
  //   technologies: ["iOS", "Alamofire", "Firebase","One Single","NISDK"],
  //   client: "Dubai",
  //   results: ["300% increase in user engagement", "50% reduction in cart abandonment", "4.8/5 app store rating"],
  //   caseStudy: {
  //     challenge: "Moos Barber needed a mobile platform that would make Barbering services accessible and engaging for everyday consumers while tracking their preferences.",
  //     solution: "We developed a React Native app with AI-powered Barber recommendations, appointment scheduling, and user-friendly interfaces to encourage bookings.",
  //     outcome: "The app achieved over 100K downloads in the first 6 months, with users reporting 40% more bookings and high engagement with the Barber profiles.",
  //     timeline: "4 months",
  //     teamSize: "6 developers",
  //     projectDetails: "Society Management Apps for Customers, Security Guards & web software for society management staff",
  //     AppHighlights: ["Resident App – Pay maintenance bills, raise complaints, book amenities, track visitors.", "Security Guard App – Quick visitor entry/exit, emergency alerts, staff attendance.", "Society Staff Web Software – Manage members, finances, facility bookings, and reports.", "Communication Hub – Announcements, polls, and notice board for residents.", "Digital Payments – Easy online payments for maintenance & utilities.", "Smart Dashboard – Real-time analytics and reports for management committees.", "Instant Alerts – SMS, push notifications & emergency notifications.", "Facility Management – Track bookings for clubhouse, gym, parking, etc.", ""],
  //     technologies: ["iOS", "Android"],
  //     thirdPartyServices: ["Alamofire", "Pushy"],
  //   },
  // },
  // {
  //   id: 13,
  //   title: "Alojeriry",
  //   category: "Mobile App",
  //   iOS_Link: "https://apps.apple.com/us/app/%D8%AA%D9%82%D9%88%D9%8A%D9%85-%D8%A7%D9%84%D8%B9%D8%AC%D9%8A%D8%B1%D9%8A/id475773742",
  //   Android_Link: "https://play.google.com/store/search?q=%D8%AA%D9%82%D9%88%D9%8A%D9%85%20%D8%A7%D9%84%D8%B9%D8%AC%D9%8A%D8%B1%D9%8A&c=apps&hl=en",

  //   type: "mobile",
  //   description: "Alojeiri Calendar (تقويم العجيري) brings all the features of the traditional paper calendar in a modern format, including both Hijri and Gregorian dates, accurate prayer times, live weather and sea conditions, Ajiriyat by Dr. Saleh Al-Ajairy, annual holidays, important events, and more—providing a complete, reliable, and fast calendar for everyday use.",
  //   image: "/Alojeriry.png",
  //   technologies: ["iOS", "Alamofire", "Firebase","One Single","NISDK"],
  //   client: "Kuwait",
  //   results: ["300% increase in user engagement", "50% reduction in cart abandonment", "4.8/5 app store rating"],
  //   caseStudy: {
  //     challenge: "Moos Barber needed a mobile platform that would make Barbering services accessible and engaging for everyday consumers while tracking their preferences.",
  //     solution: "We developed a React Native app with AI-powered Barber recommendations, appointment scheduling, and user-friendly interfaces to encourage bookings.",
  //     outcome: "The app achieved over 100K downloads in the first 6 months, with users reporting 40% more bookings and high engagement with the Barber profiles.",
  //     timeline: "4 months",
  //     teamSize: "6 developers",
  //     projectDetails: "Society Management Apps for Customers, Security Guards & web software for society management staff",
  //     AppHighlights: ["Resident App – Pay maintenance bills, raise complaints, book amenities, track visitors.", "Security Guard App – Quick visitor entry/exit, emergency alerts, staff attendance.", "Society Staff Web Software – Manage members, finances, facility bookings, and reports.", "Communication Hub – Announcements, polls, and notice board for residents.", "Digital Payments – Easy online payments for maintenance & utilities.", "Smart Dashboard – Real-time analytics and reports for management committees.", "Instant Alerts – SMS, push notifications & emergency notifications.", "Facility Management – Track bookings for clubhouse, gym, parking, etc.", ""],
  //     technologies: ["iOS", "Android"],
  //     thirdPartyServices: ["Alamofire", "Pushy"],
  //   },
  // },
  // {
  //   id: 14,
  //   title: "FitPlay",
  //   category: "Mobile App",
  //   type: "mobile",
  //    iOS_Link: "https://apps.apple.com/us/app/fitplay-app/id6739831458",
  //   Android_Link: "https://play.google.com/store/apps/details?id=com.si.fitplayapp&hl=en",

  //   description: "FitPlay is the go-to app for young athletes to easily book training sessions, track their progress, and stay updated with schedules and important notifications. Start training with top academies like the official AC Milan Academy in Kuwait. Trainers can provide feedback and share insights to help players reach their full potential. The app keeps you connected, motivated, and improving every day. More sports and training opportunities will be added soon, offering even more ways to grow. Download FitPlay today and take your game to the next level!",
  //   image: "/FitPlay.png",
  //   technologies: ["iOS", "Alamofire", "Firebase","One Single","NISDK"],
  //   client: "Kuwait",
  //   results: ["300% increase in user engagement", "50% reduction in cart abandonment", "4.8/5 app store rating"],
  //   caseStudy: {
  //     challenge: "Moos Barber needed a mobile platform that would make Barbering services accessible and engaging for everyday consumers while tracking their preferences.",
  //     solution: "We developed a React Native app with AI-powered Barber recommendations, appointment scheduling, and user-friendly interfaces to encourage bookings.",
  //     outcome: "The app achieved over 100K downloads in the first 6 months, with users reporting 40% more bookings and high engagement with the Barber profiles.",
  //     timeline: "4 months",
  //     teamSize: "6 developers",
  //     projectDetails: "Society Management Apps for Customers, Security Guards & web software for society management staff",
  //     AppHighlights: ["Resident App – Pay maintenance bills, raise complaints, book amenities, track visitors.", "Security Guard App – Quick visitor entry/exit, emergency alerts, staff attendance.", "Society Staff Web Software – Manage members, finances, facility bookings, and reports.", "Communication Hub – Announcements, polls, and notice board for residents.", "Digital Payments – Easy online payments for maintenance & utilities.", "Smart Dashboard – Real-time analytics and reports for management committees.", "Instant Alerts – SMS, push notifications & emergency notifications.", "Facility Management – Track bookings for clubhouse, gym, parking, etc.", ""],
  //     technologies: ["iOS", "Android"],
  //     thirdPartyServices: ["Alamofire", "Pushy"],
  //   },
  // },
  // {
  //   id: 15,
  //   title: "Broadway-fahion",
  //   category: "Mobile App",
  //   iOS_Link: "",
  //   Android_Link: "",

  //   type: "mobile",
  //   description: "Broadway Fashion is your ultimate fashion companion, designed to revolutionize the way you shop for clothing. Explore the latest trends and stay ahead of the curve with a vast collection from top brands and emerging designers. Get personalized style recommendations tailored to your taste and preferences. Easily browse, discover, and shop your favorite looks all in one place. Stay stylish and trendy with curated collections that match every occasion. Download Broadway Fashion today and elevate your wardrobe effortlessly!",
  //   image: "/Broadway.png",
  //   technologies: ["iOS", "Alamofire", "Firebase","One Single","NISDK"],
  //   client: "UK",
  //   results: ["300% increase in user engagement", "50% reduction in cart abandonment", "4.8/5 app store rating"],
  //   caseStudy: {
  //     challenge: "Moos Barber needed a mobile platform that would make Barbering services accessible and engaging for everyday consumers while tracking their preferences.",
  //     solution: "We developed a React Native app with AI-powered Barber recommendations, appointment scheduling, and user-friendly interfaces to encourage bookings.",
  //     outcome: "The app achieved over 100K downloads in the first 6 months, with users reporting 40% more bookings and high engagement with the Barber profiles.",
  //     timeline: "4 months",
  //     teamSize: "6 developers",
  //     projectDetails: "Society Management Apps for Customers, Security Guards & web software for society management staff",
  //     AppHighlights: ["Resident App – Pay maintenance bills, raise complaints, book amenities, track visitors.", "Security Guard App – Quick visitor entry/exit, emergency alerts, staff attendance.", "Society Staff Web Software – Manage members, finances, facility bookings, and reports.", "Communication Hub – Announcements, polls, and notice board for residents.", "Digital Payments – Easy online payments for maintenance & utilities.", "Smart Dashboard – Real-time analytics and reports for management committees.", "Instant Alerts – SMS, push notifications & emergency notifications.", "Facility Management – Track bookings for clubhouse, gym, parking, etc.", ""],
  //     technologies: ["iOS", "Android"],
  //     thirdPartyServices: ["Alamofire", "Pushy"],
  //   },
  // },
  // {
  //   id: 16,
  //   title: "OncoBuddy",
  //   category: "Mobile App",
  //    iOS_Link: "https://apps.apple.com/in/app/oncobuddy-the-cancer-care-app/id6618149164",
  //   Android_Link: "https://play.google.com/store/search?q=OncoBuddy&c=apps&hl=en",
  //   type: "mobile",
  //   description: "OncoBuddy by 4baseCare is a digital healthcare platform providing comprehensive cancer care support. It connects patients, caregivers, and clinicians, offering access to medical records, allied services (Psychology, Nutrition, Genetic Counseling, Palliative Care), and community support. OncoHub allows patients to learn, share experiences, and receive expert guidance. OncoPHR manages medical records with AI-powered organization and tagging. OncoConsult enables secure virtual consultations with oncologists, including caregiver involvement and easy appointment scheduling.",
  //   image: "/OncoBuddy.png",
  //   technologies: ["iOS", "Alamofire", "Firebase","One Single","NISDK"],
  //   client: "India",
  //   results: ["300% increase in user engagement", "50% reduction in cart abandonment", "4.8/5 app store rating"],
  //   caseStudy: {
  //     challenge: "Moos Barber needed a mobile platform that would make Barbering services accessible and engaging for everyday consumers while tracking their preferences.",
  //     solution: "We developed a React Native app with AI-powered Barber recommendations, appointment scheduling, and user-friendly interfaces to encourage bookings.",
  //     outcome: "The app achieved over 100K downloads in the first 6 months, with users reporting 40% more bookings and high engagement with the Barber profiles.",
  //     timeline: "4 months",
  //     teamSize: "6 developers",
  //     projectDetails: "Society Management Apps for Customers, Security Guards & web software for society management staff",
  //     AppHighlights: ["Resident App – Pay maintenance bills, raise complaints, book amenities, track visitors.", "Security Guard App – Quick visitor entry/exit, emergency alerts, staff attendance.", "Society Staff Web Software – Manage members, finances, facility bookings, and reports.", "Communication Hub – Announcements, polls, and notice board for residents.", "Digital Payments – Easy online payments for maintenance & utilities.", "Smart Dashboard – Real-time analytics and reports for management committees.", "Instant Alerts – SMS, push notifications & emergency notifications.", "Facility Management – Track bookings for clubhouse, gym, parking, etc.", ""],
  //     technologies: ["iOS", "Android"],
  //     thirdPartyServices: ["Alamofire", "Pushy"],
  //   },
  // },
  {
    id: 17,
    title: "DrewPIC",
    category: "Mobile App",
    iOS_Link: "https://apps.apple.com/us/app/drewpic/id1260555648",
    Android_Link: "https://play.google.com/store/apps/details?id=com.drew.drewpic&hl=en",
    type: "mobile",
    description: "drewPIC lets you react to news stories by videos. React, Record, and share your videos in 30-second clips. You can explore other video reactions as well called drewpics, drewpick or drewpics. These shirt clips you can share on various social media networks.",
    image: "/DrewPIC.png",
    technologies: ["iOS", "Alamofire", "Firebase","One Single","NISDK"],
    client: "USA",
    results: ["300% increase in user engagement", "50% reduction in cart abandonment", "4.8/5 app store rating"],
    caseStudy: {
      challenge: "Moos Barber needed a mobile platform that would make Barbering services accessible and engaging for everyday consumers while tracking their preferences.",
      solution: "We developed a React Native app with AI-powered Barber recommendations, appointment scheduling, and user-friendly interfaces to encourage bookings.",
      outcome: "The app achieved over 100K downloads in the first 6 months, with users reporting 40% more bookings and high engagement with the Barber profiles.",
      timeline: "4 months",
      teamSize: "6 developers",
      projectDetails: "Society Management Apps for Customers, Security Guards & web software for society management staff",
      AppHighlights: ["Resident App – Pay maintenance bills, raise complaints, book amenities, track visitors.", "Security Guard App – Quick visitor entry/exit, emergency alerts, staff attendance.", "Society Staff Web Software – Manage members, finances, facility bookings, and reports.", "Communication Hub – Announcements, polls, and notice board for residents.", "Digital Payments – Easy online payments for maintenance & utilities.", "Smart Dashboard – Real-time analytics and reports for management committees.", "Instant Alerts – SMS, push notifications & emergency notifications.", "Facility Management – Track bookings for clubhouse, gym, parking, etc.", ""],
      technologies: ["iOS", "Android"],
      thirdPartyServices: ["Alamofire", "Pushy"],
    },
  },
  // {
  //   id: 18,
  //   title: "Tashead Building Material",
  //   category: "Mobile App",
  //   iOS_Link: "https://apps.apple.com/us/app/tashead-building-material/id6450504288",
  //   Android_Link: "https://play.google.com/store/apps/details?id=com.SI.tashead&hl=en",
  //   type: "mobile",
  //   description: "The new Dubai Harbour Marinas mobile app is designed to ensure an impeccable docking and seafront journey. Engaging and intuitive, the fully integrated app will allow marina members to access a wide range of information and request a host of services at their fingertips. The app works seamlessly across all mobile devices and the user-friendly navigation ensures easy access to key, frequently visited sections.",
  //   image: "/Tashead.png",
  //   technologies: ["iOS", "Alamofire", "Firebase","One Single","NISDK"],
  //   client: "Kuwait",
  //   results: ["300% increase in user engagement", "50% reduction in cart abandonment", "4.8/5 app store rating"],
  //   caseStudy: {
  //     challenge: "Moos Barber needed a mobile platform that would make Barbering services accessible and engaging for everyday consumers while tracking their preferences.",
  //     solution: "We developed a React Native app with AI-powered Barber recommendations, appointment scheduling, and user-friendly interfaces to encourage bookings.",
  //     outcome: "The app achieved over 100K downloads in the first 6 months, with users reporting 40% more bookings and high engagement with the Barber profiles.",
  //     timeline: "4 months",
  //     teamSize: "6 developers",
  //     projectDetails: "Society Management Apps for Customers, Security Guards & web software for society management staff",
  //     AppHighlights: ["Resident App – Pay maintenance bills, raise complaints, book amenities, track visitors.", "Security Guard App – Quick visitor entry/exit, emergency alerts, staff attendance.", "Society Staff Web Software – Manage members, finances, facility bookings, and reports.", "Communication Hub – Announcements, polls, and notice board for residents.", "Digital Payments – Easy online payments for maintenance & utilities.", "Smart Dashboard – Real-time analytics and reports for management committees.", "Instant Alerts – SMS, push notifications & emergency notifications.", "Facility Management – Track bookings for clubhouse, gym, parking, etc.", ""],
  //     technologies: ["iOS", "Android"],
  //     thirdPartyServices: ["Alamofire", "Pushy"],
  //   },
  // },
  // {
  //   id: 19,
  //   title: "Al-Randi",
  //   category: "Mobile App",
  //    iOS_Link: "https://apps.apple.com/us/app/al-randi/id6468807711",
  //   Android_Link: "https://play.google.com/store/apps/details?id=com.si.alrandi&hl=en",
  //   type: "mobile",
  //   description: "The new Dubai Harbour Marinas mobile app is designed to ensure an impeccable docking and seafront journey. Engaging and intuitive, the fully integrated app will allow marina members to access a wide range of information and request a host of services at their fingertips. The app works seamlessly across all mobile devices and the user-friendly navigation ensures easy access to key, frequently visited sections.",
  //   image: "/Al-Randi.png",
  //   technologies: ["iOS", "Alamofire", "Firebase","One Single","NISDK"],
  //   client: "Kuwait",
  //   results: ["300% increase in user engagement", "50% reduction in cart abandonment", "4.8/5 app store rating"],
  //   caseStudy: {
  //     challenge: "Moos Barber needed a mobile platform that would make Barbering services accessible and engaging for everyday consumers while tracking their preferences.",
  //     solution: "We developed a React Native app with AI-powered Barber recommendations, appointment scheduling, and user-friendly interfaces to encourage bookings.",
  //     outcome: "The app achieved over 100K downloads in the first 6 months, with users reporting 40% more bookings and high engagement with the Barber profiles.",
  //     timeline: "4 months",
  //     teamSize: "6 developers",
  //     projectDetails: "Society Management Apps for Customers, Security Guards & web software for society management staff",
  //     AppHighlights: ["Resident App – Pay maintenance bills, raise complaints, book amenities, track visitors.", "Security Guard App – Quick visitor entry/exit, emergency alerts, staff attendance.", "Society Staff Web Software – Manage members, finances, facility bookings, and reports.", "Communication Hub – Announcements, polls, and notice board for residents.", "Digital Payments – Easy online payments for maintenance & utilities.", "Smart Dashboard – Real-time analytics and reports for management committees.", "Instant Alerts – SMS, push notifications & emergency notifications.", "Facility Management – Track bookings for clubhouse, gym, parking, etc.", ""],
  //     technologies: ["iOS", "Android"],
  //     thirdPartyServices: ["Alamofire", "Pushy"],
  //   },
  // },
  // {
  //   id: 20,
  //   title: "FreshMa : Fresh Fish & Seafood",
  //   category: "Mobile App",
  //   iOS_Link: "https://apps.apple.com/in/app/freshma/id1635380798",
  //   Android_Link: "https://play.google.com/store/apps/details?id=com.freshma.customer&hl=en",
  //   type: "mobile",
  //   description: "The new Dubai Harbour Marinas mobile app is designed to ensure an impeccable docking and seafront journey. Engaging and intuitive, the fully integrated app will allow marina members to access a wide range of information and request a host of services at their fingertips. The app works seamlessly across all mobile devices and the user-friendly navigation ensures easy access to key, frequently visited sections.",
  //   image: "/FreshMa.png",
  //   technologies: ["iOS", "Alamofire", "Firebase","One Single","NISDK"],
  //   client: "Kuwait",
  //   results: ["300% increase in user engagement", "50% reduction in cart abandonment", "4.8/5 app store rating"],
  //   caseStudy: {
  //     challenge: "Moos Barber needed a mobile platform that would make Barbering services accessible and engaging for everyday consumers while tracking their preferences.",
  //     solution: "We developed a React Native app with AI-powered Barber recommendations, appointment scheduling, and user-friendly interfaces to encourage bookings.",
  //     outcome: "The app achieved over 100K downloads in the first 6 months, with users reporting 40% more bookings and high engagement with the Barber profiles.",
  //     timeline: "4 months",
  //     teamSize: "6 developers",
  //     projectDetails: "Society Management Apps for Customers, Security Guards & web software for society management staff",
  //     AppHighlights: ["Resident App – Pay maintenance bills, raise complaints, book amenities, track visitors.", "Security Guard App – Quick visitor entry/exit, emergency alerts, staff attendance.", "Society Staff Web Software – Manage members, finances, facility bookings, and reports.", "Communication Hub – Announcements, polls, and notice board for residents.", "Digital Payments – Easy online payments for maintenance & utilities.", "Smart Dashboard – Real-time analytics and reports for management committees.", "Instant Alerts – SMS, push notifications & emergency notifications.", "Facility Management – Track bookings for clubhouse, gym, parking, etc.", ""],
  //     technologies: ["iOS", "Android"],
  //     thirdPartyServices: ["Alamofire", "Pushy"],
  //   },
  // },
  // {
  //   id: 21,
  //   title: "UVIP-Recruitment",
  //   category: "Mobile App",
  //   iOS_Link: "https://apps.apple.com/us/app/uvip-recruitment/id6450502723",
  //   Android_Link: "https://play.google.com/store/apps/details?id=com.uvip&hl=en",
  //   type: "mobile",
  //   description: "The new Dubai Harbour Marinas mobile app is designed to ensure an impeccable docking and seafront journey. Engaging and intuitive, the fully integrated app will allow marina members to access a wide range of information and request a host of services at their fingertips. The app works seamlessly across all mobile devices and the user-friendly navigation ensures easy access to key, frequently visited sections.",
  //   image: "/UVIP.png",
  //   technologies: ["iOS", "Alamofire", "Firebase","One Single","NISDK"],
  //   client: "Kuwait",
  //   results: ["300% increase in user engagement", "50% reduction in cart abandonment", "4.8/5 app store rating"],
  //   caseStudy: {
  //     challenge: "Moos Barber needed a mobile platform that would make Barbering services accessible and engaging for everyday consumers while tracking their preferences.",
  //     solution: "We developed a React Native app with AI-powered Barber recommendations, appointment scheduling, and user-friendly interfaces to encourage bookings.",
  //     outcome: "The app achieved over 100K downloads in the first 6 months, with users reporting 40% more bookings and high engagement with the Barber profiles.",
  //     timeline: "4 months",
  //     teamSize: "6 developers",
  //     projectDetails: "Society Management Apps for Customers, Security Guards & web software for society management staff",
  //     AppHighlights: ["Resident App – Pay maintenance bills, raise complaints, book amenities, track visitors.", "Security Guard App – Quick visitor entry/exit, emergency alerts, staff attendance.", "Society Staff Web Software – Manage members, finances, facility bookings, and reports.", "Communication Hub – Announcements, polls, and notice board for residents.", "Digital Payments – Easy online payments for maintenance & utilities.", "Smart Dashboard – Real-time analytics and reports for management committees.", "Instant Alerts – SMS, push notifications & emergency notifications.", "Facility Management – Track bookings for clubhouse, gym, parking, etc.", ""],
  //     technologies: ["iOS", "Android"],
  //     thirdPartyServices: ["Alamofire", "Pushy"],
  //   },
  // },
  // {
  //   id: 22,
  //   title: "Nhyira Premium",
  //   category: "Mobile App",
  //   iOS_Link: "https://apps.apple.com/us/app/nhyira-premium/id1558633746",
  //   Android_Link: "https://play.google.com/store/apps/details?id=com.webdukes.learning&hl=en",
  //   type: "mobile",
  //   description: "The new Dubai Harbour Marinas mobile app is designed to ensure an impeccable docking and seafront journey. Engaging and intuitive, the fully integrated app will allow marina members to access a wide range of information and request a host of services at their fingertips. The app works seamlessly across all mobile devices and the user-friendly navigation ensures easy access to key, frequently visited sections.",
  //   image: "/Nhyira.png",
  //   technologies: ["iOS", "Alamofire", "Firebase","One Single","NISDK"],
  //   client: "Kuwait",
  //   results: ["300% increase in user engagement", "50% reduction in cart abandonment", "4.8/5 app store rating"],
  //   caseStudy: {
  //     challenge: "Moos Barber needed a mobile platform that would make Barbering services accessible and engaging for everyday consumers while tracking their preferences.",
  //     solution: "We developed a React Native app with AI-powered Barber recommendations, appointment scheduling, and user-friendly interfaces to encourage bookings.",
  //     outcome: "The app achieved over 100K downloads in the first 6 months, with users reporting 40% more bookings and high engagement with the Barber profiles.",
  //     timeline: "4 months",
  //     teamSize: "6 developers",
  //     projectDetails: "Society Management Apps for Customers, Security Guards & web software for society management staff",
  //     AppHighlights: ["Resident App – Pay maintenance bills, raise complaints, book amenities, track visitors.", "Security Guard App – Quick visitor entry/exit, emergency alerts, staff attendance.", "Society Staff Web Software – Manage members, finances, facility bookings, and reports.", "Communication Hub – Announcements, polls, and notice board for residents.", "Digital Payments – Easy online payments for maintenance & utilities.", "Smart Dashboard – Real-time analytics and reports for management committees.", "Instant Alerts – SMS, push notifications & emergency notifications.", "Facility Management – Track bookings for clubhouse, gym, parking, etc.", ""],
  //     technologies: ["iOS", "Android"],
  //     thirdPartyServices: ["Alamofire", "Pushy"],
  //   },
  // },
  // {
  //   id: 23,
  //   title: "ARN News",
  //   category: "Mobile App",
  //   iOS_Link: "https://apps.apple.com/in/app/arn-news-centre/id1004993999",
  //   Android_Link: "https://play.google.com/store/apps/details?id=com.arn.arnnews&hl=en",
  //   type: "mobile",
  //   description: "The new Dubai Harbour Marinas mobile app is designed to ensure an impeccable docking and seafront journey. Engaging and intuitive, the fully integrated app will allow marina members to access a wide range of information and request a host of services at their fingertips. The app works seamlessly across all mobile devices and the user-friendly navigation ensures easy access to key, frequently visited sections.",
  //   image: "/ARN.png",
  //   technologies: ["iOS", "Alamofire", "Firebase","One Single","NISDK"],
  //   client: "Duba",
  //   results: ["300% increase in user engagement", "50% reduction in cart abandonment", "4.8/5 app store rating"],
  //   caseStudy: {
  //     challenge: "Moos Barber needed a mobile platform that would make Barbering services accessible and engaging for everyday consumers while tracking their preferences.",
  //     solution: "We developed a React Native app with AI-powered Barber recommendations, appointment scheduling, and user-friendly interfaces to encourage bookings.",
  //     outcome: "The app achieved over 100K downloads in the first 6 months, with users reporting 40% more bookings and high engagement with the Barber profiles.",
  //     timeline: "4 months",
  //     teamSize: "6 developers",
  //     projectDetails: "Society Management Apps for Customers, Security Guards & web software for society management staff",
  //     AppHighlights: ["Resident App – Pay maintenance bills, raise complaints, book amenities, track visitors.", "Security Guard App – Quick visitor entry/exit, emergency alerts, staff attendance.", "Society Staff Web Software – Manage members, finances, facility bookings, and reports.", "Communication Hub – Announcements, polls, and notice board for residents.", "Digital Payments – Easy online payments for maintenance & utilities.", "Smart Dashboard – Real-time analytics and reports for management committees.", "Instant Alerts – SMS, push notifications & emergency notifications.", "Facility Management – Track bookings for clubhouse, gym, parking, etc.", ""],
  //     technologies: ["iOS", "Android"],
  //     thirdPartyServices: ["Alamofire", "Pushy"],
  //   },
  // },
  // {
  //   id: 24,
  //   title: "Beauty Meditation",
  //   category: "Mobile App",
  //   iOS_Link: "https://apps.apple.com/us/app/beauty-meditation/id1470800523",
  //   Android_Link: "https://play.google.com/store/apps/details?id=com.respekt&hl=en",
  //   type: "mobile",
  //   description: "The new Dubai Harbour Marinas mobile app is designed to ensure an impeccable docking and seafront journey. Engaging and intuitive, the fully integrated app will allow marina members to access a wide range of information and request a host of services at their fingertips. The app works seamlessly across all mobile devices and the user-friendly navigation ensures easy access to key, frequently visited sections.",
  //   image: "/Beauty.png",
  //   technologies: ["iOS", "Alamofire", "Firebase","One Single","NISDK"],
  //   client: "Duba",
  //   results: ["300% increase in user engagement", "50% reduction in cart abandonment", "4.8/5 app store rating"],
  //   caseStudy: {
  //     challenge: "Moos Barber needed a mobile platform that would make Barbering services accessible and engaging for everyday consumers while tracking their preferences.",
  //     solution: "We developed a React Native app with AI-powered Barber recommendations, appointment scheduling, and user-friendly interfaces to encourage bookings.",
  //     outcome: "The app achieved over 100K downloads in the first 6 months, with users reporting 40% more bookings and high engagement with the Barber profiles.",
  //     timeline: "4 months",
  //     teamSize: "6 developers",
  //     projectDetails: "Society Management Apps for Customers, Security Guards & web software for society management staff",
  //     AppHighlights: ["Resident App – Pay maintenance bills, raise complaints, book amenities, track visitors.", "Security Guard App – Quick visitor entry/exit, emergency alerts, staff attendance.", "Society Staff Web Software – Manage members, finances, facility bookings, and reports.", "Communication Hub – Announcements, polls, and notice board for residents.", "Digital Payments – Easy online payments for maintenance & utilities.", "Smart Dashboard – Real-time analytics and reports for management committees.", "Instant Alerts – SMS, push notifications & emergency notifications.", "Facility Management – Track bookings for clubhouse, gym, parking, etc.", ""],
  //     technologies: ["iOS", "Android"],
  //     thirdPartyServices: ["Alamofire", "Pushy"],
  //   },
  // },
  // {
  //   id: 25,
  //   title: "FlyElite",
  //   category: "Mobile App",
  //   iOS_Link: "https://apps.apple.com/us/app/flyelite/id6468663680",
  //   Android_Link: "https://play.google.com/store/apps/details?id=com.booking.flyelitejets&hl=en",
  //   type: "mobile",
  //   description: "The new Dubai Harbour Marinas mobile app is designed to ensure an impeccable docking and seafront journey. Engaging and intuitive, the fully integrated app will allow marina members to access a wide range of information and request a host of services at their fingertips. The app works seamlessly across all mobile devices and the user-friendly navigation ensures easy access to key, frequently visited sections.",
  //   image: "/FlyElite.png",
  //   technologies: ["iOS", "Alamofire", "Firebase","One Single","NISDK"],
  //   client: "Duba",
  //   results: ["300% increase in user engagement", "50% reduction in cart abandonment", "4.8/5 app store rating"],
  //   caseStudy: {
  //     challenge: "Moos Barber needed a mobile platform that would make Barbering services accessible and engaging for everyday consumers while tracking their preferences.",
  //     solution: "We developed a React Native app with AI-powered Barber recommendations, appointment scheduling, and user-friendly interfaces to encourage bookings.",
  //     outcome: "The app achieved over 100K downloads in the first 6 months, with users reporting 40% more bookings and high engagement with the Barber profiles.",
  //     timeline: "4 months",
  //     teamSize: "6 developers",
  //     projectDetails: "Society Management Apps for Customers, Security Guards & web software for society management staff",
  //     AppHighlights: ["Resident App – Pay maintenance bills, raise complaints, book amenities, track visitors.", "Security Guard App – Quick visitor entry/exit, emergency alerts, staff attendance.", "Society Staff Web Software – Manage members, finances, facility bookings, and reports.", "Communication Hub – Announcements, polls, and notice board for residents.", "Digital Payments – Easy online payments for maintenance & utilities.", "Smart Dashboard – Real-time analytics and reports for management committees.", "Instant Alerts – SMS, push notifications & emergency notifications.", "Facility Management – Track bookings for clubhouse, gym, parking, etc.", ""],
  //     technologies: ["iOS", "Android"],
  //     thirdPartyServices: ["Alamofire", "Pushy"],
  //   },
  // },
  //  {
  //   id: 26,
  //   title: "Toffaha",
  //   category: "Mobile App",
  //   iOS_Link: "https://apps.apple.com/us/app/toffaha/id1174256710",
  //   Android_Link: "",
  //   type: "mobile",
  //   description: "The new Dubai Harbour Marinas mobile app is designed to ensure an impeccable docking and seafront journey. Engaging and intuitive, the fully integrated app will allow marina members to access a wide range of information and request a host of services at their fingertips. The app works seamlessly across all mobile devices and the user-friendly navigation ensures easy access to key, frequently visited sections.",
  //   image: "/DHM.png",
  //   technologies: ["iOS", "Alamofire", "Firebase","One Single","NISDK"],
  //   client: "Duba",
  //   results: ["300% increase in user engagement", "50% reduction in cart abandonment", "4.8/5 app store rating"],
  //   caseStudy: {
  //     challenge: "Moos Barber needed a mobile platform that would make Barbering services accessible and engaging for everyday consumers while tracking their preferences.",
  //     solution: "We developed a React Native app with AI-powered Barber recommendations, appointment scheduling, and user-friendly interfaces to encourage bookings.",
  //     outcome: "The app achieved over 100K downloads in the first 6 months, with users reporting 40% more bookings and high engagement with the Barber profiles.",
  //     timeline: "4 months",
  //     teamSize: "6 developers",
  //     projectDetails: "Society Management Apps for Customers, Security Guards & web software for society management staff",
  //     AppHighlights: ["Resident App – Pay maintenance bills, raise complaints, book amenities, track visitors.", "Security Guard App – Quick visitor entry/exit, emergency alerts, staff attendance.", "Society Staff Web Software – Manage members, finances, facility bookings, and reports.", "Communication Hub – Announcements, polls, and notice board for residents.", "Digital Payments – Easy online payments for maintenance & utilities.", "Smart Dashboard – Real-time analytics and reports for management committees.", "Instant Alerts – SMS, push notifications & emergency notifications.", "Facility Management – Track bookings for clubhouse, gym, parking, etc.", ""],
  //     technologies: ["iOS", "Android"],
  //     thirdPartyServices: ["Alamofire", "Pushy"],
  //   },
  // },
  // {
  //   id: 27,
  //   title: "Funcom",
  //   category: "Mobile App",
  //    iOS_Link: "https://apps.apple.com/us/app/funcom/id1111184012",
  //   Android_Link: "https://play.google.com/store/apps/details?id=com.funcom.android&hl=en",
  //   type: "mobile",
  //   description: "The new Dubai Harbour Marinas mobile app is designed to ensure an impeccable docking and seafront journey. Engaging and intuitive, the fully integrated app will allow marina members to access a wide range of information and request a host of services at their fingertips. The app works seamlessly across all mobile devices and the user-friendly navigation ensures easy access to key, frequently visited sections.",
  //   image: "/Funcom.png",
  //   technologies: ["iOS", "Alamofire", "Firebase","One Single","NISDK"],
  //   client: "Duba",
  //   results: ["300% increase in user engagement", "50% reduction in cart abandonment", "4.8/5 app store rating"],
  //   caseStudy: {
  //     challenge: "Moos Barber needed a mobile platform that would make Barbering services accessible and engaging for everyday consumers while tracking their preferences.",
  //     solution: "We developed a React Native app with AI-powered Barber recommendations, appointment scheduling, and user-friendly interfaces to encourage bookings.",
  //     outcome: "The app achieved over 100K downloads in the first 6 months, with users reporting 40% more bookings and high engagement with the Barber profiles.",
  //     timeline: "4 months",
  //     teamSize: "6 developers",
  //     projectDetails: "Society Management Apps for Customers, Security Guards & web software for society management staff",
  //     AppHighlights: ["Resident App – Pay maintenance bills, raise complaints, book amenities, track visitors.", "Security Guard App – Quick visitor entry/exit, emergency alerts, staff attendance.", "Society Staff Web Software – Manage members, finances, facility bookings, and reports.", "Communication Hub – Announcements, polls, and notice board for residents.", "Digital Payments – Easy online payments for maintenance & utilities.", "Smart Dashboard – Real-time analytics and reports for management committees.", "Instant Alerts – SMS, push notifications & emergency notifications.", "Facility Management – Track bookings for clubhouse, gym, parking, etc.", ""],
  //     technologies: ["iOS", "Android"],
  //     thirdPartyServices: ["Alamofire", "Pushy"],
  //   },
  // },
  // {
  //   id: 28,
  //   title: "Boomerang Logistics (Navigation)",
  //   category: "Mobile App",
  //    iOS_Link: "https://apps.apple.com/us/app/boomerang-logistics/id6739403001",
  //   Android_Link: "https://play.google.com/store/apps/details?id=boomerang.mylogistics.store&hl=en",
  //   type: "mobile",
  //   description: "The new Dubai Harbour Marinas mobile app is designed to ensure an impeccable docking and seafront journey. Engaging and intuitive, the fully integrated app will allow marina members to access a wide range of information and request a host of services at their fingertips. The app works seamlessly across all mobile devices and the user-friendly navigation ensures easy access to key, frequently visited sections.",
  //   image: "/Boomerang.png",
  //   technologies: ["iOS", "Alamofire", "Firebase","One Single","NISDK"],
  //   client: "Duba",
  //   results: ["300% increase in user engagement", "50% reduction in cart abandonment", "4.8/5 app store rating"],
  //   caseStudy: {
  //     challenge: "Moos Barber needed a mobile platform that would make Barbering services accessible and engaging for everyday consumers while tracking their preferences.",
  //     solution: "We developed a React Native app with AI-powered Barber recommendations, appointment scheduling, and user-friendly interfaces to encourage bookings.",
  //     outcome: "The app achieved over 100K downloads in the first 6 months, with users reporting 40% more bookings and high engagement with the Barber profiles.",
  //     timeline: "4 months",
  //     teamSize: "6 developers",
  //     projectDetails: "Society Management Apps for Customers, Security Guards & web software for society management staff",
  //     AppHighlights: ["Resident App – Pay maintenance bills, raise complaints, book amenities, track visitors.", "Security Guard App – Quick visitor entry/exit, emergency alerts, staff attendance.", "Society Staff Web Software – Manage members, finances, facility bookings, and reports.", "Communication Hub – Announcements, polls, and notice board for residents.", "Digital Payments – Easy online payments for maintenance & utilities.", "Smart Dashboard – Real-time analytics and reports for management committees.", "Instant Alerts – SMS, push notifications & emergency notifications.", "Facility Management – Track bookings for clubhouse, gym, parking, etc.", ""],
  //     technologies: ["iOS", "Android"],
  //     thirdPartyServices: ["Alamofire", "Pushy"],
  //   },
  // },
  // {
  //   id: 29,
  //   title: "QCC Boomerang (Quality Commercial Cleaning)",
  //   category: "Mobile App",
  //    iOS_Link: "https://apps.apple.com/us/app/qcc-boomerang/id6478601662",
  //   Android_Link: "https://play.google.com/store/apps/details?id=boomerang.qcc.cleaning&hl=en",
  //   type: "mobile",
  //   description: "The new Dubai Harbour Marinas mobile app is designed to ensure an impeccable docking and seafront journey. Engaging and intuitive, the fully integrated app will allow marina members to access a wide range of information and request a host of services at their fingertips. The app works seamlessly across all mobile devices and the user-friendly navigation ensures easy access to key, frequently visited sections.",
  //   image: "/QCC.png",
  //   technologies: ["iOS", "Alamofire", "Firebase","One Single","NISDK"],
  //   client: "Duba",
  //   results: ["300% increase in user engagement", "50% reduction in cart abandonment", "4.8/5 app store rating"],
  //   caseStudy: {
  //     challenge: "Moos Barber needed a mobile platform that would make Barbering services accessible and engaging for everyday consumers while tracking their preferences.",
  //     solution: "We developed a React Native app with AI-powered Barber recommendations, appointment scheduling, and user-friendly interfaces to encourage bookings.",
  //     outcome: "The app achieved over 100K downloads in the first 6 months, with users reporting 40% more bookings and high engagement with the Barber profiles.",
  //     timeline: "4 months",
  //     teamSize: "6 developers",
  //     projectDetails: "Society Management Apps for Customers, Security Guards & web software for society management staff",
  //     AppHighlights: ["Resident App – Pay maintenance bills, raise complaints, book amenities, track visitors.", "Security Guard App – Quick visitor entry/exit, emergency alerts, staff attendance.", "Society Staff Web Software – Manage members, finances, facility bookings, and reports.", "Communication Hub – Announcements, polls, and notice board for residents.", "Digital Payments – Easy online payments for maintenance & utilities.", "Smart Dashboard – Real-time analytics and reports for management committees.", "Instant Alerts – SMS, push notifications & emergency notifications.", "Facility Management – Track bookings for clubhouse, gym, parking, etc.", ""],
  //     technologies: ["iOS", "Android"],
  //     thirdPartyServices: ["Alamofire", "Pushy"],
  //   },
  // },
  // {
  //   id: 30,
  //   title: "1000 Islands CruiseMate",
  //   category: "Mobile App",
  //    iOS_Link: "https://apps.apple.com/us/app/1000-islands-cruisemate/id6451207002",
  //   Android_Link: "https://play.google.com/store/apps/details?id=com.funcom.android&hl=en",
  //   type: "mobile",
  //   description: "The new Dubai Harbour Marinas mobile app is designed to ensure an impeccable docking and seafront journey. Engaging and intuitive, the fully integrated app will allow marina members to access a wide range of information and request a host of services at their fingertips. The app works seamlessly across all mobile devices and the user-friendly navigation ensures easy access to key, frequently visited sections.",
  //   image: "/DHM.png",
  //   technologies: ["iOS", "Alamofire", "Firebase","One Single","NISDK"],
  //   client: "Duba",
  //   results: ["300% increase in user engagement", "50% reduction in cart abandonment", "4.8/5 app store rating"],
  //   caseStudy: {
  //     challenge: "Moos Barber needed a mobile platform that would make Barbering services accessible and engaging for everyday consumers while tracking their preferences.",
  //     solution: "We developed a React Native app with AI-powered Barber recommendations, appointment scheduling, and user-friendly interfaces to encourage bookings.",
  //     outcome: "The app achieved over 100K downloads in the first 6 months, with users reporting 40% more bookings and high engagement with the Barber profiles.",
  //     timeline: "4 months",
  //     teamSize: "6 developers",
  //     projectDetails: "Society Management Apps for Customers, Security Guards & web software for society management staff",
  //     AppHighlights: ["Resident App – Pay maintenance bills, raise complaints, book amenities, track visitors.", "Security Guard App – Quick visitor entry/exit, emergency alerts, staff attendance.", "Society Staff Web Software – Manage members, finances, facility bookings, and reports.", "Communication Hub – Announcements, polls, and notice board for residents.", "Digital Payments – Easy online payments for maintenance & utilities.", "Smart Dashboard – Real-time analytics and reports for management committees.", "Instant Alerts – SMS, push notifications & emergency notifications.", "Facility Management – Track bookings for clubhouse, gym, parking, etc.", ""],
  //     technologies: ["iOS", "Android"],
  //     thirdPartyServices: ["Alamofire", "Pushy"],
  //   },
  // },
];
