import type { MetadataRoute } from "next"
import { siteConfig } from "@/lib/seo-config"

// ============================================================
// Dynamic robots.txt — auto-generated by Next.js
// Accessible at: /robots.txt
// ============================================================
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: ["/api/", "/_next/", "/admin/"],
      },
    ],
    sitemap: `${siteConfig.url}/sitemap.xml`,
  }
}
